export enum PROJECTION_EVENTS {
  USER_ONBOARDED_PROJECTION_EVENT = 'USER_ONBOARDED_PROJECTION_EVENT',
  USER_PROFILE_UPDATED_PROJECTION_EVENT = 'USER_PROFILE_UPDATED_PROJECTION_EVENT',
  VIDEO_PUBLISHED_PROJECTION_EVENT = 'VIDEO_PUBLISHED_PROJECTION_EVENT',
  CHANNEL_CREATED_PROJECTION_EVENT = 'CHANNEL_CREATED_PROJECTION_EVENT',
}
