export enum MESSAGE_BUS_EXCEPTION {
  MESSAGE_BUS_CONNECTION_EXCEPTION = 'MESSAGE_BUS_CONNECTION_EXCEPTION',
  MESSAGE_BUS_TIMEOUT_EXCEPTION = 'MESSAGE_BUS_TIMEOUT_EXCEPTION',
  MESSAGE_BUS_UNKNOWN_EXCEPTION = 'MESSAGE_BUS_UNKNOWN_EXCEPTION',
}
