export enum Entity {
  COMMENT = 'COMMENT',
  REACTION = 'REACTION',
  USER = 'USER',
  USER_PROJECTION = 'USER_PROJECTION',
  VIDEO_PROJECTION = 'VIDEO_PROJECTION',
  VIDEO = 'VIDEO',
  VIEW = 'VIEW',
}
