export enum USER_EVENTS {
  USER_LANGUAGE_CHANGED_EVENT = 'USER_LANGUAGE_CHANGED_EVENT',
  USER_NOTIFICATION_CHANGED_EVENT = 'USER_NOTIFICATION_CHANGED_EVENT',
  USER_ONBOARDED_EVENT = 'USER_ONBOARDED_EVENT',
  USER_PHONE_NUMBER_UPDATED_EVENT = 'USER_PHONE_NUMBER_UPDATED_EVENT',
  USER_THEME_CHANGED_EVENT = 'USER_THEME_CHANGED_EVENT',
  USER_PROFILE_UPDATED_EVENT = 'USER_PROFILE_UPDATED_EVENT',
}
